#sdk: "/Users/Ryota/.rvm/gems/ruby-1.9.3-p194@rhodes/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: event
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.event
  BundleURLScheme: event
wp:
  productid: 'af0480c0-bc4d-012f-250e-3c07542aa8a3'
symbian:
  uid: '0xefd444d5'
android:
  version: 2.3.3
capabilities:
- calendar
extensions: ["json", "another-extension"]
